### ISSUE TITLE
The WOOF automatic filter disappears when I install this plugin

### ISSUE THREAD

**Issue by radi-cho** [kagg-design/woof-by-category#1]
### Hello. When I install your plugin and turn it on the filter on my shop goes away.

Before filter:
<img width="1440" alt="Screenshot 2020-04-07 at 11 42 28" src="https://user-images.githubusercontent.com/12954909/78648612-dde64400-78c4-11ea-9465-7ea8879c4bd2.png">

After filter:
<img width="1440" alt="Screenshot 2020-04-07 at 11 42 42" src="https://user-images.githubusercontent.com/12954909/78648633-e6d71580-78c4-11ea-853f-1eda7ed9895c.png">

## Do you have any suggestions why this might happen and how to properly fix it.

> Note: My categories are in cyrillic script.

<img width="1440" alt="Screenshot 2020-04-07 at 11 43 56" src="https://user-images.githubusercontent.com/12954909/78648729-138b2d00-78c5-11ea-996d-6e9d014aa868.png">

<img width="280" alt="Screenshot 2020-04-07 at 11 44 33" src="https://user-images.githubusercontent.com/12954909/78648778-29005700-78c5-11ea-94c1-0b2fc4a160b7.png">

**Comment by kagg-design** [comment]
Apologies for a late answer, please try to use the latest versions of WOOf and WOOf by Category. I have fixed similar bugs.

**Comment by radi-cho** [comment]
Marking issue as not relevant anymore.
Will reopen if needed. Thanks.
