### ISSUE TITLE
Значение атрибута по категориям

### ISSUE THREAD

**Issue by Julihina** [kagg-design/woof-by-category#3]
На сайте много категорий и атрибутов
Атрибуты в некоторых категориях пересекаются, например, мощность есть почти во всех подкатегориях для Электроинструмента
Проблема в том, что фильтр тянет значения атрибутов со всех категорий, а нужно чтобы тянул только с той, что сейчас выводится. Пример, в "Фрезерные машины", в фильтре(WOOF) по "Мощность, Вт" https://i.imgur.com/XjTTUWY.png минимальное значение 0,5, а максимальное 36000, но таких значений в этой категории нет, они принадлежат другим. А вот, стандартный фильтр от Woocommerce выводит правильные значения https://i.imgur.com/CJgygKw.png и мне нужно чтобы фильтр от WOOF выводил такие же значения
Как я делала:
Добавляла фильтр по атрибутам в самом woof, потом в "Woof by category" добавляла к нужным категориям атрибуты, которые нужно вывести.

**Comment by kagg-design** [comment]
Покажите настройки WOOF и WOOF by Category.
